version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "2055:2055/udp"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  controller:
    build:
      context: ./Controller
    container_name: controller
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mydatabase
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  routerclient:
    build:
      context: ./RouterClient
    container_name: routerclient
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - rabbitmq
    ports:
      - "4000:4000"

  # transportmonitor:
  #   build:
  #     context: ./transportmonitor
  #   container_name: transportmonitor
  #   environment:
  #     - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq
  #   ports:
  #     - "5000:5000"

volumes:
  es_data:
    driver: local
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
